import type { NextPage } from "next";
import Inicio from "src/modules/inicio";

const Home: NextPage = () => {
  // return (
  //   <div>
  //     <Head>
  //       <title>Desenvolvimento Web</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main>
  //       <p>
  //         Participe do nosso{" "}
  //         <a
  //           href="https://chat.whatsapp.com/HTt7FwitQ9v6GnJ0VywgQw"
  //           target="_blank"
  //           rel="noopener noreferrer"
  //         >
  //           grupo do whatsapp
  //         </a>
  //       </p>
  //     </main>
  //   </div>
  // );

  return <Inicio />;
};

export default Home;
